<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="GridView.aspx.cs" Inherits="OnlineInsurance.GridView" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:GridView ID="UserData" runat="server" AutoGenerateColumns="false" DataKeyNames="customerId" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowCancelingEdit="UserGrid_RowCancelingEdit" OnRowDeleting="UserGrid_RowDeleting" OnRowEditing="UserGrid_RowEditing" OnRowUpdating="UserGrid_RowUpdating" CellSpacing="4" ShowFooter="true">
        <Columns>
            <asp:TemplateField HeaderText="CustomerName">
                <EditItemTemplate>
                    <asp:TextBox ID="textCustomerName" runat="server" Text='<%# Bind("customerName")%>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelCustomerName" runat="server" Text='<%# Bind("customerName") %>'></asp:Label>
                </ItemTemplate>
                 <FooterTemplate>
                <asp:TextBox ID="txtCustomerNameFooter" runat="server"></asp:TextBox>
                </FooterTemplate>
                <FooterTemplate>
                    <asp:TextBox ID="txtCustomerNameFooter" runat="server"></asp:TextBox>
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="CustomerId">
                <EditItemTemplate>
                    <asp:TextBox ID="textCustomerId" runat="server" Text='<%# Container.DataItemIndex +1 %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelCustomerId" runat="server" Text='<%# Bind("customerId") %>'></asp:Label>
                </ItemTemplate>
                <FooterTemplate>
               <asp:LinkButton ID="linkInsert" runat="server" Text="Insert" OnClick="linkInsert_Click"></asp:LinkButton>
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="PolicyNumber">
                <EditItemTemplate>
                    <asp:TextBox ID="textPolicyNumber" runat="server" Text='<%# Bind("policyNumber") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelPolicyNumber" runat="server" Text='<%# Bind("policyNumber") %>'></asp:Label>
                </ItemTemplate>
                 <FooterTemplate>
                    <asp:TextBox ID="txtPolicyNumberFooter" runat="server"></asp:TextBox>
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="PhoneNumber">
                <EditItemTemplate>
                    <asp:TextBox ID="textPhoneNumber" runat="server" Text='<%# Bind("phoneNumber") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelPhoneNumber" runat="server" Text='<%# Bind("phoneNumber") %>'></asp:Label>
                </ItemTemplate>
                  <FooterTemplate>
                    <asp:TextBox ID="txtPhoneNumberFooter" runat="server"></asp:TextBox>
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="DateOfBirth">
                <EditItemTemplate>
                    <asp:TextBox ID="textDateOfBirth" runat="server" Text='<%# Bind("dateofBirth") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelDateOfBirth" runat="server" Text='<%# Bind("dateofBirth") %>'></asp:Label>
                </ItemTemplate>
                  <FooterTemplate>
                    <asp:TextBox ID="txtDateOfBirthFooter" runat="server"></asp:TextBox>
                </FooterTemplate> 
                </asp:TemplateField>
               <asp:TemplateField HeaderText="MailId">
                <EditItemTemplate>
                    <asp:TextBox ID="textMailId" runat="server" Text='<%# Bind("mailId") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelMailId" runat="server" Text='<%# Bind("mailId") %>'></asp:Label>
                </ItemTemplate>
                  <FooterTemplate>
                    <asp:TextBox ID="txtMailIdFooter" runat="server"></asp:TextBox>
                </FooterTemplate>
            </asp:TemplateField>
             <asp:TemplateField HeaderText="Password">
                <EditItemTemplate>
                    <asp:TextBox ID="textPassword" runat="server" Text='<%# Bind("password") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelPassword" runat="server" Text='<%# Bind("password") %>'></asp:Label>
                </ItemTemplate>
                  <FooterTemplate>
                    <asp:TextBox ID="txtPasswordFooter" runat="server"></asp:TextBox>
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Role">
                <EditItemTemplate>
                    <asp:TextBox ID="textRole" runat="server" Text='<%# Bind("role") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="labelRole" runat="server" Text='<%# Bind("role") %>'></asp:Label>
                </ItemTemplate>
                  <FooterTemplate>
                    <asp:TextBox ID="txtRoleFooter" runat="server"></asp:TextBox>
                </FooterTemplate>
            </asp:TemplateField>
           </Columns>
    </asp:GridView>
    <br/>
        <asp:Label ID="labelsuccess" runat="server" foreColor="Green" text="" />
         <br/>
        <asp:Label ID="labelfailure" runat="server" foreColor="red" text="" />
</asp:Content>
